Fix Superset image and upgrade to 1.4.1
opendatahub-io/odh-images pull request #12
Opened 2022-03-17 19:19 UTC by rimolive

2022-03-18 01:30 UTC, anishasthana requested changes

2022-03-18 01:30 UTC, anishasthana commented on superset/Makefile
> +	container-structure-test test -i $(IMAGE_NAME) -c test-config.yaml
Missing new line

2022-03-18 01:30 UTC, anishasthana commented on superset/README.md
>  The application should now be accessible at  [http://localhost:8080](http://localhost:8080).
The command above is specifying `port 8088` but in the doc we are saying `8080`

2022-03-18 01:30 UTC, anishasthana commented on superset/README.md
> +docker run -d -p 8088:8088 <your-desired-image-name>
Why not `podman` :-)

2022-03-18 01:30 UTC, anishasthana commented on superset/Makefile
> +BUILDER:=$(shell command -v docker 2> /dev/null || command -v podman 2> /dev/null || echo "docker or podman not found")
Could we swap the other on this to check for podman first?

2022-03-18 01:36 UTC, anishasthana commented
The make build is failing for me

```
Errors during downloading metadata for repository 'rhel-8-for-x86_64-baseos-beta-rpms':
  - Status code: 403 for https://cdn.redhat.com/content/beta/rhel8/8/x86_64/baseos/os/repodata/repomd.xml (IP: 23.49.52.251)
Error: Failed to download metadata for repo 'rhel-8-for-x86_64-baseos-beta-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

What specific rights do we need?

2022-03-21 22:17 UTC, rimolive commented
@anishasthana I'm not sure where/how you tried to build the image, but I got a fresh CoreOS VM and I could build the image with no issues.

I know that UBI usually relies on the repos that are enabled in the host, so that might be what happened to you.

2022-03-25 02:09 UTC, LaVLaS commented
I did get a similar error with a different repo.  I think it may have been an issue to the repo mirror redirection.  

```
Errors during downloading metadata for repository 'rhel-8-for-x86_64-appstream-beta-rpms':
  - Status code: 403 for https://cdn.redhat.com/content/beta/rhel8/8/x86_64/appstream/os/repodata/repomd.xml (IP: 173.222.100.251)
Error: Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-beta-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

I think the presence of subscription-manager on the host machine is causing issues with the reposync process

2022-03-30 12:24 UTC, anishasthana reviewed
I was able to successfully build on another machine. /lgtm

2022-03-30 12:24 UTC, anishasthana approved these changes

2022-03-31 11:34 UTC, merged